### PR TITLE
add french translation

### PR DESCRIPTION
**Pull request by VincentGuyader**
please find in this PR some french translation from the ThinkR team

Regards

### CODE REVIEW

**Comment by VincentGuyader** [comment]
@gvwilson  this is for you :)

Regards

**Comment by garrettgman** [comment]
Thanks @VincentGuyader, this is excellent.

**Comment by garrettgman** [comment]
@VincentGuyader the RSCloud team does not currently have a strategy for displaying translated primers. In the mean time, I have deployed these primers to shinyapps.io, where they can be accessed at:
* https://tutorials.shinyapps.io/02-Vis-Basics-fr/
* https://tutorials.shinyapps.io/04-Programming-Basics-fr/
* https://tutorials.shinyapps.io/01-Reshape-Data-fr/
* https://tutorials.shinyapps.io/02-separate-columns-fr/
* https://tutorials.shinyapps.io/03-join-datasets-fr/
* https://tutorials.shinyapps.io/01-tibbles-fr/
* https://tutorials.shinyapps.io/02-isolating-fr/
* https://tutorials.shinyapps.io/03-deriving-fr/
* https://tutorials.shinyapps.io/01-bar-charts-fr/
* https://tutorials.shinyapps.io/02-Exploratory-Data-Analysis-fr/
* https://tutorials.shinyapps.io/03-histograms-fr/
* https://tutorials.shinyapps.io/04-boxplots-fr/
* https://tutorials.shinyapps.io/05-scatterplots-fr/
* https://tutorials.shinyapps.io/06-line-graphs-fr/
* https://tutorials.shinyapps.io/07-overplotting-fr/
* https://tutorials.shinyapps.io/08-Customize-fr/

**Comment by garrettgman** [comment]
...but I may have assumed too much :) Is your intention to have these available in RStudio Cloud?

**Pull request merged**
