### PR TITLE
Adding License and Code of Conduct

### PR DESCRIPTION
**Pull request by gvwilson**
- CC-BY license
- Contributor Covenant

### CODE REVIEW

**Comment by garrettgman** [comment]
Thanks @gvwilson! Can you please make two modifications?

* The license should be CC BY-NC-ND 3.0 to match R4DS. We reused parts of that book in the primers with the publisher's permission under the understanding that we were not changing the license.

* Can you replace the Code of Conduct with the one adopted by the Tidyverse team, here? https://github.com/tidyverse/ggplot2/blob/master/CODE_OF_CONDUCT.md

**Comment by gvwilson** [comment]
1. Updating the CoC.
2. If we use 3.0, the -ND clause will prevent Yanina and others from creating any derivative works or remixes they create (see https://en.wikipedia.org/wiki/Creative_Commons_license). If we use 4.0, they will be able to create those derivative works but not distribute them. Can we therefore agree on CC-BY-NC ?

**Comment by garrettgman** [comment]
1. Thanks for aligning the CoC with the Tidyverse team!
2. For the CC, it is not a matter of persuasion because I agree with you. It is contract compliance :( That said, using copyrighted material to teach is a protected fair use under US copyright law. In addition to that, the likelihood that RStudio or O'Reilly would choose to prosecute anyone for reusing the primers is vanishingly small. So is the likelihood that either could show the clear presence of copyrighted material in the primers. I sympathize that changing the copyright would provide teachers CYA, but it would remove our own CYA. Speaking of CYA, I'm happy to refer this to a legal mind greater than mine.

**Comment by gvwilson** [comment]
When you say "contract compliance" is this the contract w/ O'Reilly for R4DS? In which case I agree our hands are tied. The problem is that Yanina wants to create translations:

> Hello everyone, I am putting together a series of tutorials with learnr and there are some exercises of the primers that I would like to use within my tutorials (it would be a translation to be precise), Can I do it? If I can, How can I quote it?

which definitely count as "derivative works" :-/

**Pull request merged**
